apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-api-exp-input
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150G

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-api-exp-data
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200G

---

apiVersion: v1
kind: Pod
metadata:
  name: exp-pod
  namespace: user
spec:
  containers:
  - name: exp-pod
    image: ubuntu
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    workingDir: /input
    volumeMounts:
      - mountPath: /input
        name: input
      - mountPath: /data
        name: data
    securityContext:
      runAsUser: 0
  nodeSelector: 
    cwsscheduler: 'true'
  volumes:
  - name: input
    persistentVolumeClaim:
      claimName: ceph-api-exp-input
  - name: data
    persistentVolumeClaim:
      claimName: ceph-api-exp-data
  securityContext:
    runAsUser: 0